InternetShopAspNetCoreMvc/ViewModels/CategoryViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace InternetShopAspNetCoreMvc.ViewModels
{
    public class CategoryViewModel
    {
        [Required]
        [MaxLength(50)]
        public string Name { get; set; }

        [MaxLength(200)]
        public string Description { get; set; }
    }
}

InternetShopAspNetCoreMvc/Controllers/CartController.cs
using InternetShopAspNetCoreMvc.Models;
using InternetShopAspNetCoreMvc.Repositories.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace InternetShopAspNetCoreMvc.Controllers
{
	public class CartController : Controller
	{
		private readonly ICartRepository _cartRepository;
		private const int UserId = 1;

        public CartController(ICartRepository cartRepository)
		{
			_cartRepository = cartRepository;
		}

		public async Task<IActionResult> Index()
		{
            return View( await _cartRepository.GetUserCartItemsAsync(UserId));
		}

		[HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddToCart(CartItem item)
		{
			item.UserId = UserId;
             await _cartRepository.AddToCartAsync(item);

			return RedirectToAction("Index", "Products");
		}

		public async Task<IActionResult> EmptyCart()
		{
            await _cartRepository.DeleteAllUserCartItemsAsync(UserId);

			return RedirectToAction("Index");
		}

		[HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var cartItem = await _cartRepository.GetCartItemAsync(id);

            if (cartItem != null)
            {
                return View(cartItem);
            }

            return View("DoesNotExist");
        }

		[HttpPost]
		public async Task<IActionResult> Edit(CartItem item) 
		{
            await _cartRepository.AddToCartAsync(item);

			return RedirectToAction("Index");
		}

        public async Task<IActionResult> Delete(int id)
		{
			var cartItem = await _cartRepository.GetCartItemAsync(id);

			if (cartItem != null)
			{
               await _cartRepository.DeleteUserCartItemAsync(cartItem.Id);
			}

			return RedirectToAction("Index");
		}
	}
}

InternetShopAspNetCoreMvc/Controllers/CategoriesController.cs
using InternetShopAspNetCoreMvc.Models;
using InternetShopAspNetCoreMvc.Repositories.Interfaces;
using InternetShopAspNetCoreMvc.Service.Interfaces;
using InternetShopAspNetCoreMvc.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace InternetShopAspNetCoreMvc.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly ICategoryService _categoryService;

        public CategoriesController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }
        public async Task<IActionResult> Index()
        {
            var categories = await _categoryService.GetAllCategoryAsync();
            return View(categories);
        }

        public async Task<IActionResult> Manage()
        {
            var categories = await _categoryService.GetAllCategoryAsync();
            return View(categories);
        }

        public async Task<IActionResult> Details(int id)
        {
            var category = await _categoryService.GetByIdCategoryAsync(id);

            if (category == null)
            {
                return View("DoesNotExist");
            }

            return View(category);
        }

        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CategoryViewModel categoryVM)
        {
            if (!ModelState.IsValid)
            {
                return View(categoryVM);
            }

            var category = new Category
            {
                Name = categoryVM.Name,
                Description = categoryVM.Description,
                CreatedAt = DateTime.UtcNow
            };

            await _categoryService.CreateCategoryAsync(category);

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Edit(int id)
        {
            var category = await _categoryService.GetByIdCategoryAsync(id);

            if (category == null)
            {
                return View("DoesNotExist");
            }

            return View(category);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Category category)
        {
            if (id != category.Id)
            {
                return BadRequest();
            }

            if (!ModelState.IsValid)
            {
                return View(category);
            }

            await _categoryService.UpdateCategoryAsync(category);

            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }

            var category = await _categoryService.GetByIdCategoryAsync(id.Value);

            if (category == null)
            {
                return View("DoesNotExist");
            }

            return View(category);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _categoryService.DeleteCategoryAsync(id);

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> CategoryProducts(int id)
        {
            var category = await _categoryService.GetByIdCategoryAsync(id);

            if (category == null)
            {
                return View("DoesNotExist");
            }

            return View(category);
        }
    }
}

InternetShopAspNetCoreMvc/Views/Categories/CategoryProducts.cshtml
@model InternetShopAspNetCoreMvc.Models.Category

<h1>@Model.Name</h1>
<h2>@Model.Description</h2>
<br />

<div class="d-flex justify-content-around flex-wrap align-content-around">
    @foreach (var product in Model.Products)
    {
        var imageUrl = product.Image.StartsWith("/")
        ? product.Image
        : Url.Content($"~/images/Products/{product.Image}");

        <div class="card mb-4" style="width: 300px;">
            <img class="card-img-top"
                 src="@imageUrl"
                 alt="@product.Name" />

            <div class="card-body">
                <h4 class="card-title">@product.Name</h4>
                <h5 class="card-subtitle mb-2 text-muted">
                    @product.Price.ToString("N0") ₴
                </h5>
                <p class="card-text">@product.Description</p>

                <form asp-action="AddToCart" asp-controller="Cart" method="post">
                    <input type="hidden" name="ProductId" value="@product.Id" />
                    <div class="input-group mb-3">
                        <label class="input-group-text" for="Quantity">Quantity</label>
                        <input type="number"
                               id="Quantity"
                               name="Quantity"
                               value="1"
                               class="form-control" />
                        <button type="submit"
                                class="btn btn-outline-secondary">
                            Add To Cart
                        </button>
                    </div>
                </form>
            </div>
        </div>
    }
</div>

@if (!Model.Products.Any())
{
    <h3>No Products Available in this Category</h3>
}

InternetShopAspNetCoreMvc/Views/Categories/Create.cshtml
@using InternetShopAspNetCoreMvc.ViewModels;
@model CategoryViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Add Category</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Add Category" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

InternetShopAspNetCoreMvc/Views/Categories/Delete.cshtml
@model Category

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Category</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>
    </dl>
    
    <form asp-action="DeleteConfirmed">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

InternetShopAspNetCoreMvc/Views/Categories/Details.cshtml
@model Category

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Category</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

InternetShopAspNetCoreMvc/Views/Categories/Edit.cshtml
@model Category

@{
    ViewData["Title"] = "Edit";



}

<h1>Edit</h1>
<h4>Category</h4>
<hr />


<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="All" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="CreatedAt" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

InternetShopAspNetCoreMvc/Views/Categories/Index.cshtml
@model IEnumerable<Category>

@{
	ViewData["Title"] = "Index";
}

<h1>Index</h1>

<table class="table">
	<thead>
		<tr>
			<th>
				@Html.DisplayNameFor(model => model.Name)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Description)
			</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model)
		{
			<tr>
				<td>
					@Html.DisplayFor(modelItem => item.Name)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Description)
				</td>
				<td>
					<a class="btn btn-primary" href="Categories/CategoryProducts/@item.Id">See Products</a>
				</td>
			</tr>
		}
	</tbody>
</table>

<br />

InternetShopAspNetCoreMvc/Views/Categories/Manage.cshtml
@model IEnumerable<Category>

@{
	ViewData["Title"] = "Index";
}

<h1>Index</h1>

<table class="table">
	<thead>
		<tr>
			<th>
				@Html.DisplayNameFor(model => model.Name)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Description)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.CreatedAt)
			</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model)
		{
			<tr>
				<td>
					@Html.DisplayFor(modelItem => item.Name)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Description)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.CreatedAt)
				</td>
				<td>
					<a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
					<a asp-action="Details" asp-route-id="@item.Id">Details</a> |
					<a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
				</td>
			</tr>
		}
	</tbody>
</table>

<br />
<a type="button" class="btn btn-dark" asp-controller="Categories" asp-action="Create">Add a Category</a>